[workspace]
members = [
    "ocaml-gen",
    "ocaml-gen/derive",
    "tests/ocamlgen_test_stubs"
]
resolver = "2"

[workspace.dependencies]
convert_case = "*"
ocaml = "0.22.4"
const-random = "*"
paste = "*"
proc-macro2 = "*"
quote = "*"
syn = { version = "2", features = ["full"] }
